config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
    root 'notes#index', as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.where(user_id: current_user).order('created_at DESC')
    @note = current_user.notes.build
  end

  def show
  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)
    respond_to do |format|
      if @note.save
        format.js
      else
        render 'new'
      end
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to notes_path
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private
  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Unote
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  %body.index#page-top
    =render 'partials/menu'
    -# %p.notice= notice
    -# %p.alert= alert

    -# %div.container
    = yield

    =render 'partials/footer'

app/views/notes/_form.html.erb
<%= simple_form_for @note do |f|%>
<form role="form">
  <div class="form-group">
     <%= f.label :title %>
     <%= f.input_field :title, class:"form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
     <%=f.input_field :content, as: :text, input_html: {rows: 10, cols: 38}, class:"form-control"  %>
  </div>
     <%=f.button :submit %>
</form>
<% end %>

app/views/notes/create.js.erb
$("#newModal").modal("hide");
$("#noteTitle").val("");
$("#noteContent").val("");
$("#notes").prepend("<h2><div id= <%= @note.id %>><%= j link_to @note.title, @note %></div></h2> <%= time_ago_in_words(@note.created_at)%>").addClass( "floating-box" )
$("#<%= @note.id %>").addClass( "animated shake" );

app/views/notes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1> Edit Your Note </h1>

      <%= render 'form' %>

      <%= link_to "Cancel", note_path %>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<div class="container">
<style>
  i {
    vertical-align: middle;
  }

/*.floating-box {
    float: left;
    height: 75px;
    margin: 25px;
    /*border: 3px solid #73AD21;*/
}*/


</style>
<br/>
<!-- Large modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-md">Add Note</button>

<div class="modal fade bs-example-modal-md" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="newModal">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title" id="myModalLabel">New Note</h4>
     </div>
     <div class="container">
      <div class="row">
          <div class="col-md-6">
            <%= simple_form_for @note, remote: true do |f|%>
            <form role="form">
              <div class="form-group">
                 <%= f.label :title %>
                 <%= f.input_field :title, class:"form-control", id:"noteTitle"  %>
              </div>
              <div class="form-group">
                <%= f.label :content %>
                 <%=f.input_field :content, as: :text, input_html: {rows: 10, cols: 38}, class:"form-control", id:"noteContent"  %>
              </div>
                 <%=f.button :submit %>
            </form>
            <% end %>
            <br/>
             </div>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="notes">
  <%@notes.each do |note|%>
  <div id="<%=note.id%>" class="floating-box">
    <h2><%= link_to note.title, note%></h2>
    <%= time_ago_in_words(note.created_at)%>
  </div>
  <% end %>
</div>



</div>

app/views/notes/new.html.erb
<h1> New note </h1>

<%= render 'form' %>

app/views/notes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
<h1> <%= @note.title %></h1>
<p>
  <%= simple_format(@note.content) %>
</p>

<%= link_to '<i class="material-icons">home</i>'.html_safe, notes_path %>
<%= link_to '<i class="material-icons">mode_edit</i>'.html_safe,  edit_note_path(@note) %>
<%= link_to '<i class="material-icons">delete</i>'.html_safe, note_path(@note), method: :delete, data:{ confirm: "Are you sure?"}  %>
    </div>
  </div>
</div>

<script type="text/javascript">
$("[data-behavior='delete']").on("click", function(e){
  e.preventDefault()

  swal {
      title: 'Are you sure?'
      text: 'You will not be able to recover this imaginary file!'
      type: 'warning'
      showCancelButton: true
      confirmButtonColor: '#DD6B55'
      confirmButtonText: 'Yes, delete it!'
      cancelButtonText: 'No, cancel plx!'
      closeOnConfirm: false
      closeOnCancel: false
    }
});
</script>

app/views/partials/_footer.html.erb
<!-- Footer -->
<div class="navbar-fixed-bottom">
    <footer class="text-center">
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Juan Huttemann - 2016
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>

app/views/partials/_menu.html.erb
<!-- Navigation -->
<style media="screen">
  .navbar {
    margin-bottom: 0px;
    border-radius: 0px;
  }
</style>
<nav id="mainNav" class="navbar navbar-default navbar-custom">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <%= link_to "U-Note", root_path, class:"navbar-brand"%>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <% if user_signed_in?%>
                <li class="page-scroll"><%= link_to('Log out', destroy_user_session_path, :method => :delete) %></li>
                <% else %>
                <li class="page-scroll">
                  <%= link_to "Register", new_user_registration_path%>
                </li>
                <li class="page-scroll">
                    <%= link_to "Log In", new_user_session_path%>
                </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<style media="screen">
  a {
    color:#333;
  }

  a:hover {
    color:#18BC9C;
    text-decoration:none;
  }

  header {
    background-color: #fff;
  }

  header .container {
    padding-top: 100px;
    /*padding-bottom: 200px;*/
  }


  @media (max-width: 480px) {
    header .container {
      /*padding-top: 100px;*/
      /*padding-bottom: 300px;*/
    }
  }

  @media (max-width: 768px) {
    header .container {
      /*padding-top: 100px;*/
      /*padding-bottom: 300px;*/
    }
  }


</style>

<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <img class="img-responsive" src="/notepad.png" alt="">
                <div class="intro-text">

                    <a href="/users/sign_in"><span class="name">Start Now</span></a>
                </div>
            </div>
        </div>
    </div>
</header>